title: Monica Vargas
logo: assets/fotoo.jpeg
description: ¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
include:
  - assets
  - README.md
baseurl: "https://github.com/monik719/port/blob/main"
